### ISSUE TITLE
Demo run on Linux gives "FileNotFoundError: [Errno 2] No such file or directory: '.../ALICE/model'

### ISSUE THREAD

**Issue by choward232** [orasanen/ALICE#22] opened 2021-08-16 00:16 UTC
After installing ALICE and creating the conda environment, a demo run results in a file not found error as mentioned in the title. Here is a screenshot!

![error](https://user-images.githubusercontent.com/46383794/129497027-ead5d91b-a300-4e95-8916-59cd11fee83f.PNG)

**Comment by orasanen** [comment] 2021-10-27 05:43
I assume you have been using macOS? This issue has been (finally) resolved in #23 , and was caused by some change in pyannote and mac compatibility. Please re-install following the instructions in the updated docs, and let me know if you still encounter this problem.

**Closed as completed by orasanen** 2021-10-27 05:43 UTC
